### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by mhamTech** [bratan/flutter_translate#100]
Please update all the library packages because it is prevent us from using other packages in our project.

Like for example:
intl
path
and some other important libraries.

**Comment by kristofb** [comment]
That is not possible, if you try it locally, you'll get:
Because every version of flutter_translate from git depends on intl ^0.18.0 and every version of flutter_localizations from sdk depends on intl 0.17.0, flutter_translate from git is incompatible with flutter_localizations from sdk.

**Comment by cjouannet** [comment]
Any updates?

**Comment by tomc128** [comment]
Newer versions of flutter (in the beta channel) ship with a version of `flutter_localizations` that requires `intl >= 0.18.0`, rendering these Flutter versions incompatible with this plugin. Maybe a 5.x.x version could update intl and should be used for any Flutter versions requiring 0.18.0? There's a pull request already open which updates the intl dependency, #103
