### ISSUE TITLE
Parent Widget not updated

### ISSUE THREAD

**Issue by Ahmedklai** [bratan/flutter_translate#102]
The problem is when i changed for german as showing below for example , only the current widget changed and the TabBar is not changing until set the state ..
Even though i’m using the onLocalChanged function 
![simulator_screenshot_ED0639CD-5529-4577-BA62-DA10857D35F1](https://user-images.githubusercontent.com/60032213/216372328-2eee8af1-56b6-43f5-8d80-043c433d7633.png)

**Comment by mironsaid** [comment]
Have you found a solution for this?
