### ISSUE TITLE
Add information for the deprecated flutter_translate_gen

### ISSUE THREAD

**Issue by Leptopoda** [bratan/flutter_translate#104]
Currently flutter_translate_gen isn't marked as archived by pub.dev.

Also the Readme still points to it :)

**Comment by renrique92** [comment]
@Leptopoda hey bro, do you use this? How you continue to use the flutter_translate_gen to generate the keys? I have to do it manually right now

**Comment by Leptopoda** [comment]
I'm not using it and when I last looked into it it wasn't worth porting it to the new versions.

going forward I'm migrating my the project away from this package to support the flutter native translation tool (sadly transifex doesn't support it).

**Comment by Leptopoda** [comment]
Bump
