### ISSUE TITLE
No MaterialLocalizations found , If change language to Soomaali  (so) 

### ISSUE THREAD

**Issue by vyas-git** [bratan/flutter_translate#105]
Getting this error 
The following message was thrown:
Warning: This application's locale, so, is not supported by all of its
localization delegates.

• A MaterialLocalizations delegate that supports the so locale was not found.
• A CupertinoLocalizations delegate that supports the so locale was not found.

The declared supported locales for this app are: en, so, ar

See https://flutter.dev/tutorials/internationalization/ for more information
about configuring an
app's locale, supportedLocales, and localizationsDelegates parameters.
════════════════════════════════════════════════════════════════════════════════
════════════════════
Another exception was thrown: No MaterialLocalizations found.
Another exception was thrown: No MaterialLocalizations found.

**Comment by bratan** [comment]
I don't think this issue is related to `flutter_translate` and you should probably post it in the `Flutter` repo.

**Comment by vyas-git** [comment]
Yes only these are supported by Flutter 
https://api.flutter.dev/flutter/flutter_localizations/flutter_localizations-library.html

https://github.com/aissat/easy_localization/issues/220 this helps me .
