### ISSUE TITLE
universal_io, Question about?

### ISSUE THREAD

**Issue by skaiya-ai** [bratan/flutter_translate#114]
Please, can you explain why you need this package, "universal_io," inside this translation package?

**Comment by bratan** [comment]
It was used instead of ```dart:io``` (which is not supported on Web) to access ```Platform.localeName```.

<img width="337" alt="image" src="https://github.com/Jesway/flutter_translate/assets/5787988/0c34fe46-831e-41d9-8e68-7574708383fb">

It was replaced & removed in version 5.0 (pre-release currently).
