### ISSUE TITLE
Upgrade the package to use the latest version of "intl"

### ISSUE THREAD

**Issue by wasilni2022** [bratan/flutter_translate#121]
Hello, since Flutter has been upgraded and Dart has also been upgraded to 3.4.0, the package must now use intl 0.19.0 or above, because the old version prevents the project from using the benefits of the new Flutter enhancements and features.

**Comment by skaiya-ai** [comment]
Yes, we need that update ASAP, the whole project stopped and we can't even run pub get any more because it is said:

Flutter pinned to intl 0.19.0 but flutter_translate 4.0.4 pinned to 0.18.0, pub get failed.

Please update the package ASAP.

**Comment by wasilni2022** [comment]
Any updates ? is the developer of this package still active ?

**Comment by bratan** [comment]
@wasilni2022 @arabnology - Feel free to submit a PR.

**Comment by wasilni2022** [comment]
> @wasilni2022 @arabnology - Feel free to submit a PR.

Please, are you planning to continue updating this package or should we use another? because we are waiting for your updates as soon as you can! It prevents us from using the latest version of Flutter and its features as well.

**Comment by FetFrumos** [comment]
try adding it to your pubspec

```
dependency_overrides:
  intl: 0.19.0
```

it is working for me

**Comment by wasilni2022** [comment]
> try adding it to your pubspec
> 
> ```
> dependency_overrides:
>   intl: 0.19.0
> ```
> 
> it is working for me

Where?
In the project pubspec or in the package pubspec?

If in the project, I already did this, but when I run "pub get packages", I got this error message: "flutter_translate depand on intl 0.18.0 but flutter depand on intl 0.19.0"

**Comment by Judimax** [comment]
add like this 

```
dependencies:
  ...
dev_dependencies:
   ...
dependency_overrides:
  intl: ^0.19.0
```

**Comment by arabnology** [comment]
> add like this
> 
> ```
> dependencies:
>   ...
> dev_dependencies:
>    ...
> dependency_overrides:
>   intl: ^0.19.0
> ```
> 
> I submitted a pretty big PR (the package had no test cases we wrote test cases for the whole package) in order for flutter translate to support lists in your json along with maps, the maintainer said they do not have time. They were even to introduce breaking changes in to v5.0 with more features. reach out to **** we may look into maintaining it

Worked, thank you.

**Comment by Judimax** [comment]
@arabnology were maintaining it until the original maintainer decides to work on it again https://pub.dev/packages/windmillcode_flutter_translate

**Comment by bratan** [comment]
All packages are now upgraded in [version 4.1.0](https://pub.dev/packages/flutter_translate)
