### ISSUE TITLE
Null safety access to WidgetsBinding.instance

### ISSUE THREAD

**Issue by jiazhengshi** [bratan/flutter_translate#83]
https://github.com/Jesway/Flutter-Translate/blob/master/lib/src/utils/device_locale.dart#L13

```
Try accessing using ?. instead.
  final deviceLocales = WidgetsBinding.instance.window.locales;
```

**Comment by bratan** [comment]
It's not necessary, neither the instance nor the window can be null. If this was the case it wouldn't compile otherwise.

**Comment by bratan** [comment]
@jiazhengshi - It seems this issue occurs in the stable channel and https://github.com/Jesway/Flutter-Translate/pull/85 fixes it.

**Comment by jiazhengshi** [comment]
thanks
