### ISSUE TITLE
Plural - ignores all above 2

### ISSUE THREAD

**Issue by davidhorac3** [bratan/flutter_translate#87]
Plural translation keys works only on 0, 1, 2 keys... everything else is ignore and goes right into "else" branch.

**Comment by bratan** [comment]
The plural feature uses https://pub.dev/packages/intl and seems to work correctly in the example app.  

https://pub.dev/documentation/intl/latest/intl/Intl/plural.html

**Comment by davidhorac3** [comment]
Ah, haven't noticed that it's a problem of another dependency, sry. I've just clicked into code and saw switch case with 0, 1, 2, else cases.
