### ISSUE TITLE
Pluralization feature not working for static keys

### ISSUE THREAD

**Issue by oysteinhodne** [bratan/flutter_translate#92]
It seems like the generation of plural keys is not working correctly at the moment. 
The generated keys file in the static_keys example does not generate the key "Plural.demo", only the children of it (Plural.demo.zero etc.). Which in turn gives a compilation error when I try to use the key in my widget, as the key does not exist.

I thought originally i was doing something wrong, but the generated files in the example also does this.

![image](https://user-images.githubusercontent.com/3032384/178266942-643922fe-91b7-4baa-b2de-577327ebc326.png)

Am i correct in assuming that the example will not work either? Or am i doing something wrong when i get the compilation error when running:

`translatePlural(Keys.Plural_Demo, _counter)`

**Comment by bratan** [comment]
I think the generation of plural keys needs to be updated in `flutter_translate_gen` in order for pluralization to work correctly after the latest changes in `flutter_translate`.

I don't have time currently to update the generator.

**Comment by faustodc** [comment]
This issue shouldn't be closed if it's not resolved, it's still a problem.

**Comment by bratan** [comment]
This issue is related to [Flutter-Translate-Gen](https://github.com/Jesway/Flutter-Translate-Gen ) which is discontinued and is not going to be updated any longer.

**Comment by faustodc** [comment]
Sorry for not realizing that, then perhaps the readme and wiki should be updated to reflect that.
