### ISSUE TITLE
en.json missing from assets

### ISSUE THREAD

**Issue by Appikorn** [bratan/flutter_translate#99]
/flutter (29230): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "assets/i18n/en.json".
E/flutter (29230): The asset does not exist or has empty data.

**Comment by kristofb** [comment]
Do you have 
flutter:
    assets:
    - assets/i18n/


in your pubspec file ?

and assets/i18n/en.json in your project folder?

**Comment by vindolin** [comment]
I encountered the same problem and it turned out that it was the missing trailing slash in my pubspec file.
The missing slash is also on the documentation page under _1. Installation, Configuration & Usage_.
